#cloud-config
packages:
  - docker
runcmd:
  - sudo docker run -d -p 8080:8080 -name task18app davidlitest/task18app:latest
  - sudo docker run -d -p 80:80 -name task18web --link task18app:task18app davidlitest/task18app:latest
